blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/go-taas/go-taas/discussions
    about: Please ask questions and start discussions in GitHub Discussions.
